server:
  port: 8888
spring:
  application:
    name: msklb-p-itmt-denv-config-provider
  cloud:
    config:
      server:
        git:
          order: 2
          uri: ${CONFIG_SERVER_URI}
          clone-on-start: true
          default-label: develop
        encrypt.enabled: false
        native:
          order: 1
          searchLocations: "[classpath:/, classpath:/config, classpath:/config/{application}, classpath:/config/{application}/{profile}]"         
  profiles:
     active: git,native
  security:
    user:
      name: ${CONFIG_SERVER_NAME}
      password: ${CONFIG_SERVER_PASSWORD}