FROM  openjdk:11
EXPOSE 8761/tcp
ARG JAR_FILE=target/*.jar
WORKDIR /usr/local/runme

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]

HEALTHCHECK --interval=30s --timeout=30s CMD curl -f http://localhost:8761/actuator/health || exit 1
